#!/usr/bin/env bash

# Use Java's keytool to create a JKS key store containing a freshly ground,
# self-signed, delightfully insecure server certificate to use for TLS ops.

keystoreName="smuggler-keystore"
keystorePass="changeit"

smugglerKeyAlias="smuggler"
smugglerKeyPass="changeit"



keytool -genkeypair                      \
        -alias "${smugglerKeyAlias}"     \
        -keyalg RSA                      \
        -keysize 2048                    \
        -validity 360                    \
        -keypass "${smugglerKeyPass}"    \
        -keystore "${keystoreName}.jks"  \
        -storetype JKS                   \
        -storepass "${keystorePass}"
