!!ome.smuggler.config.items.MountPointsConfig
enableTranslation: false
remoteToLocalMap:
- {localMount: /mnt/d1, remotePrefix: 'file://host1/data'}
- {localMount: /mnt/d2, remotePrefix: 'file://host2/data'}
